apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      run: probe-demo
  template:
    metadata:
      labels:
        run: probe-demo
    spec:
      containers:
      - image: deekshithsn/probe-demo
        name: probe-demo
        env:
        - name: START_DELAY
          value: "60"        
        ports:
        - containerPort: 8080